### ISSUE TITLE
Improve Overall Cadasta Cartography

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#11]
## Skills Needed
- Design skills
- A web map design technology such as CartoCSS
## First Task

Create a user account, organization and project on Cadasta's [demo system](https://demo.cadasta.org). Create a custom questionnaire for your project (documentation to assist is [here](http://docs.cadasta.org/en/08-XLSForms.html)). Once your questionnaire is created enter some data through the website or using ODK. After you have some data design a custom tileset to compliment data you are collecting in your project. You can use any software you would like to design the custom tileset. 
## Project Description

Cadasta provides maps in much of our platform. There is much improvement that can be made in the cartography of our maps. This internship will focus on improving that cartography. Two majors places to start are:

Cadasta currently uses the default OpenStreetMap tiles for our basemap. In the future we'd like to use a custom basemap that compliments the type of features our users are mapping and the regions where we are working. There are examples of other [tile sets](http://wiki.openstreetmap.org/wiki/Tile_servers) using OpenStreetMap data that do this for other uses, such as OpenCycleMap and the HOT Style (which is humanitarian focused). Cadasta needs a design that works well in two conditions that we focus on, urban slums and rural areas with small hold farmers. Though these two areas are very different it should be possible to make an appealing base map for both. 

The Cadasta vector data users are creating. Currently we overlay vector information on top of basemaps. The vector information are typically boundaries or points of interest drawn by users. At the moment the data all looks the same no matter what type of feature is being mapped. We would like to improve how this looks and compliment the overall look and feel of the Cadasta platform. A base cartography for location types should be designed as part of the internship for the Cadasta platform. 

Possible mentors: @oliverroick @clash99

**Comment by AnnaMag** [comment]
hi All! Is this project still available?

**Comment by wonderchook** [comment]
Yes, all the projects that still have open github issues are available.

**Comment by dj-m** [comment]
Hi! I'm very interested at tackling this project and love map design. 

I've created a basemap of San Jose to complement the data extracted from the San Jose Open Data portal demo map [here](https://demo.cadasta.org/organizations/any-given-sunday/projects/san-jose-open-data-portal-affordable-housing/). 

What's the best way to provide that basemap? (MBTiles export from Tilemill, CartoCSS code as a github repo, file as a 'Resource' on demo Cadasta... another way?)

**Comment by wonderchook** [comment]
@dj-m really up to you. The format we weren't too concerned with at this point and time, more your process to create it. How about a CartoCSS code and an image as a repo in github?
