### ISSUE TITLE
Create PDFs for Printing from Project Schema

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#12]
## Skills Needed
- Python/Django
## First Task

Find a bug and attempt to fix it. You can find possible bugs [here](https://github.com/Cadasta/cadasta-platform/issues) or you can look for them yourself. 

If fixing the bug went well try the following: Create a user account, organization and project on Cadasta's [demo system](https://demo.cadasta.org). Create a custom questionnaire for your project (documentation to assist is [here](http://docs.cadasta.org/en/08-XLSForms.html)). Once you've created you project design a form to print in HTML.  
## Project Description

Cadasta uses the [XLSForm standard](http://xlsform.org/) to create custom data schemas for projects in our platform. Currently there is no way to print the XLSForms from the Cadasta platform if a user wants to do paper based data collection. This proposed Outreachy project is to add the functionality to create custom printed forms within Cadasta's platform. The idea will be to generate an HTML representation of the form and turn it into a PDF using an existing library. There may be some existing software to do this conversion, so initial research is needed first. 
## User Stories
- As a user I want to be able to download my XLSForm as a PDF
- As a user I want to be able to add instructions to my PDF Form
- As a user I want to be able to upload my logo to my PDF Form
- As a user I want to be able to add a title to my PDF Form
- As a user I want to be able to modify the paper size of my PDF Form
- As a user I want to be able to modify the layout of my PDF Form
### Creating XLSForm
1. User selects "Create XLSForm for Download"
2. Page offers user upload dialogue to upload their logo, text box to enter instructions and text box to enter title. Basic markdown formatting is allowed for the instructions text box
3. User clicks next
4. User is presented with draft of form for download
5. User can move fields to create better workflow for data collection
6. User clicks finish
7. User is presented PDF file to download
## Ancillary Information

The form design where fields are moved should be left for last. The other aspects of the feature are more important. 

Possible Mentors: @oliverroick @seav

**Comment by kavindya89** [comment]
Very interesting project @wonderchook. I'll do some initial research on this area and get back with some details.

**Comment by Prateechi** [comment]
Hi @wonderchook,
We meet again :-D
This is a fantastic project. This one worth working for (y). I think I have idea to go about it (Its the field of my major project). Will send you the complete approach in sometime.

**Comment by kavindya89** [comment]
@wonderchook I have few question regarding the project. After doing some initial research, I have following questions in my mind.

The project idea is basically for convert XLSForm to PDF form. As you mentioned in the steps, user will first input basic XSLForm for PDF genaration form where when we generates the PDF form we need to add additional details such as logo, title and etc right? So basically wizard need to have a upload box for uploading XSLForm.

Also we will have a separate wizard to generates the PDF form out of a XSLForm. As cadasta already used XSLForm to HTML form rendering library. There are multiple libraries we can use to generates HTML form to PDF form. We will require to do a careful evaluation on best fit.

**Comment by wonderchook** [comment]
@kavindya89 so I realized I was thinking about this a bit wrong. Cadasta eventually wants to move away from creating the project schemas from the XLSForms. So the paper/pdf forms should be created out of the individual project schema instead of using the XLSForm. Makes it a little more complicated, but will be better in the long run.

**Comment by kavindya89** [comment]
@wonderchook thanks for the input. 

Is it mean that we will have a form design wizard separately and use it when create project schemas?

Or will user define the forms while project creation wizard going on?

**Comment by wonderchook** [comment]
I think the form design will happen after the project creation wizard has completed. Not all projects will need to print PDF forms for data collection.

**Comment by kavindya89** [comment]
@wonderchook . So we will need separate view to create a HTML form which outputs a PDF form which will be use to collect the data.
