### ISSUE TITLE
Improve Testing for Cadasta Platform

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#13]
## Skills Needed
- Knowledge of a programming language
- Basic familiarity with software testing
- Selenium
## First Task

Find a bug and create a [Selenium Test](http://www.seleniumhq.org/) that detects that bug. Extra points if you can point out in Cadasta's code where the bug is occurring. Bonus, bonus points if you fix the bug. 

If that was pretty easy design a Selenium test to completely test one feature of Cadasta's platform. Run your test [here](https://platform-staging-api.cadasta.org), don't worry about messing things up since it is Cadasta's testing site. 
## Project Description

Cadasta currently performs Unit Tests and Functional Tests as part of our development process. Every release we also perform manual testing. We'd like to improve our test coverage by creating test scripts to run against our staging/demo/production servers to confirm that everything is working properly. We've begun creating an inventory of [Manual Test Cases](https://docs.google.com/spreadsheets/d/1JmKVAmdQgjdzg8YhrSDtfBtWckkv7aq4-ZIZCmwbbwU/edit#gid=0) which is incomplete but we plan to eventually automate. This internship will be involved in improving Manual Test Case coverage and converting those test cases to automated tests. 

Possible Mentor: @wonderchook

**Comment by manoramahp** [comment]
@wonderchook 
I'd like to contribute to this improve automated testing for cadasta. I tried to run existing selenium tests that are mentioned in the wiki, but unable to proceed since https://devwiki.corp.cadasta.org/Running%20functional%20tests wiki is outdated. Could you please guide me on how to achieve this?

**Comment by ian-ross** [comment]
@manoramahp The documentation is out of date, but it should be pretty obvious what to do. There's a directory called `functional_tests` at the top level of the repository with a script called `run.py` in it. Have you tried running that script?

**Comment by manoramahp** [comment]
@ian-ross Yes i tried and got the functional tests running successfully.

**Comment by manoramahp** [comment]
@wonderchook I've gone through the Manual Test Cases doc mentioned in the project description. It seems all of these manual test cases are not implemented as automated tests. Shall I start with automating those test cases?

**Comment by wonderchook** [comment]
@manoramahp how about start with the first task which was to find a bug and create a Selenium test to detect it.

**Comment by zeddmaxx** [comment]
I would like to work on this :)

**Comment by aakanshavatsa** [comment]
Hi @wonderchook - I am interested to work on this project as part of Outreachy, and I was planning to write the Selenium tests for some of the issues already logged. 
Can I go ahead with the same? I am confident to finish the task within 2 days.
Also which repo should I push the Selenium code? Can you please let me know that as well?

Much thanks!

**Comment by wonderchook** [comment]
Go ahead. Just make a repo on your own github accound and share a link for
feedback.

**Comment by manoramahp** [comment]
@wonderchook I've found the UI bug https://github.com/Cadasta/cadasta-platform/issues/835 and made selenium tests and also the fix for the bug in the PR https://github.com/Cadasta/cadasta-platform/pull/838

**Comment by manoramahp** [comment]
While being familiar with the available selenium tests in Cadasta, I've found out these tests mostly cover only the happy path scenarios and doesn't include much of other routines.

**Comment by aakanshavatsa** [comment]
@wonderchook - The tests can be written in any programming language, Am I correct - I can select Java and Selenium Webdriver to cover the testing?

**Comment by oliverroick** [comment]
@aakanshavatsa We would prefer if we can stick to technology, we are already using in our stack. The majority of our platform's code is written in Python. Unless there is a very good reason for Java, we should write those tests in Python too.

**Comment by aakanshavatsa** [comment]
Hi @oliverroick, As part of my Outreachy task for this project, I have written the tests using Java-testNG-Webdriver combination. 

Since the tests can be language agnostic and no particular language was mentioned in the description, I went ahead and implemented using Java.

The said tests can definitely converted to Python, will not take much effort.

I can discuss further with you and @wonderchook in the upcoming days regarding the same - As I will continue to contribute to this task and edit my application as well.

Much thanks for your inputs!

**Comment by aakanshavatsa** [comment]
Hi,

Here is a summary of my completed tasks:

1. Find a bug : https://github.com/Cadasta/cadasta-platform/issues/844
2. Selenium test to detect the bug : https://github.com/aakanshavatsa/CadastaAutomationProject/blob/master/src/test/java/cadasta/tests/editprofile/ResetPasswordTest.java

3. Code change and bug fix PR : https://github.com/Cadasta/cadasta-platform/pull/846

4. Selenium tests for one Cadasta Feature:
https://github.com/aakanshavatsa/CadastaAutomationProject/blob/master/src/test/java/cadasta/tests/editprofile/ProfileUpdateTests.java
(5 tests automated around Edit Profile scenario. Code modularized and leveraged testNG and Maven for a robust and efficient design. Helper utilities written which can be leveraged by any selenium test.)
Currently these tests are in Java, but I can definitely convert them to Python as part of my final project application and, if selected, my internship as well, if that is the general consensus.

@wonderchook , @oliverroick - Would love to hear your thoughts.
 
I am submitting my application in the meantime - detailing the way I am planning to go about this particular project as part of the Outreachy internship with respect to manual and automation testing.

Thanks!

**Comment by aakanshavatsa** [comment]
Hi @wonderchook - I have submitted my application for this project.

Request you to kindly have a look at my proposed timeline for this project here : https://docs.google.com/document/d/15E6Y0nrc-D7XrHr11mSy8vvxKgpWDc8CjmGJAXm7Zc4/edit?usp=sharing
