### ISSUE TITLE
Browser Based Data Collection Tool

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#14]
## Skills Needed
- HTML
- JavaScript

## First Task
Find a bug and attempt to fix it. You can find possible bugs [here](https://github.com/Cadasta/cadasta-platform/labels/First%20Contribution%20Friendly) or you can look for them yourself.  If that goes well create a project in Cadasta. Documentation is [here](https://docs.cadasta.org/en/) to help you get started. Be creative in your project, go try to create real data for it. You can use paper or Android phones to collect your data if you have one. 

## Project Description
Currently most users collect data using [ODK-collect](https://opendatakit.org/use/collect/) or enter paper based forms into a web interface. The goal of this project is to give users a way to enter data from their mobile phone through the browser while offline. This will allow users without Android phones or others that can't use ODK a way to collect data from their phones offline. The first part of this project will be experimenting to determine that best way to approach this. 

### Key Features to Accomplish for the Project
Features are ranked in order of importance. 
- Ability to load form from Cadasta onto a mobile phone and disconnect from the internet
- Ability to enter data from individual records and save them offline.
- Once online again submit records to Cadasta
- Access the phone's GPS to gather location based data
- Restore/recover data if browser crashes
- Collect photos (this may be trickier)
- Download existing records on to the phone to be updated
- Collect data to update existing records
- Submit updated records to Cadasta

**Possible mentor:** @oliverroick

**Comment by SteadyCadence** [comment]
* Restore/recover data if browser crashes
* Collect photos (this may be trickier)

**Comment by mehulsr** [comment]
@oliverroick @wonderchook I am interested in taking up this project for Outreachy. Working on issue #922 now.

**Comment by KhirwalSumeet** [comment]
@wonderchook  I am interested in taking up this project for Outreachy.

**Comment by SteadyCadence** [comment]
Those interested in this project may want to start looking at https://serviceworke.rs and other service worker resources.  :1st_place_medal:

**Comment by ruthran011** [comment]
@wonderchook I am interested doing this project for Google Summer of Code

**Comment by Shruti9520** [comment]
@wonderchook I have a doubt regarding the sixth point i.e `Collect photos`. Is it about collecting photos while offline or something else?

**Comment by wonderchook** [comment]
@Shruti9520 if you look at resources in the Cadasta platform that is what the photos would be. This entire project needs to work offline, photos included.

**Comment by mayuri0192** [comment]
@wonderchook I am interested in taking up this project for Google Summer of Codes

**Comment by wonderchook** [comment]
@mayuri0192 great, thanks for your interest

**Comment by Shruti9520** [comment]
@wonderchook What do you think would be better for accessing location-based data- (1) Native browser API Navigator OR (2) HTML5 geolocation?
According to me, Native browser API Navigator should be used because HTML5 geolocation is not suitable for long running tracking applications.
Waiting for your reply. :)
Thanks

**Comment by Shruti9520** [comment]
@wonderchook I have some doubts regarding following-
1.`Download existing records on to the phone to be updated`
     What I understood here is when we do changes online, then offline cached data is not changed with it. 
     In order to do that, Service workers should be updated.
2.`Collect data to update existing records`
    From this, do you meant the same as stated above in my point?
    
 Thanks :)

**Comment by Shruti9520** [comment]
@wonderchook Can I know where cadasta stores photos file in the online version i.e on s3 server or on any private cloud? Also, what is the average size of file?

**Comment by oliverroick** [comment]
We're storing files on S3. We don't have information on average file sizes; it depends what type of resource it is. A video is larger than an image or a PDF.

**Comment by Shruti9520** [comment]
@oliverroick Thanks :)

**Comment by khantaalaman** [comment]
@oliverroick I had a doubt, please clarify whenever possible. 
Quick question: Do we need to save Sent Forms (or submitted records) also in the local db like ODK does?

**Comment by oliverroick** [comment]
I'm not sure if I understand your question. The data collected using this tool should be stored in the platform data base. Or do you mean that the raw form data is kept besides the processed data that results in locations, relationships and parties?

**Comment by khantaalaman** [comment]
@oliverroick The doubt is cleared now.

Thanks!

**Comment by amplifi** [comment]
Closing temporarily; to be re-opened when next participating in Outreachy or GSoC.
