### ISSUE TITLE
Additional Login Options

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#15]
## Skills Needed
- Python
- Django
- JavaScript

## First Task
Find a bug and attempt to fix it. You can find possible bugs [here](https://github.com/Cadasta/cadasta-platform/labels/First%20Contribution%20Friendly) or you can look for them yourself.  If that goes well create a project in Cadasta. Documentation is [here](https://docs.cadasta.org/en/) to help you get started. Be creative in your project, go try to create real data for it. You can use paper or Android phones to collect your data if you have one. 

## Project Description
Currently Cadasta allows users to login with their email address. Not all of our users have email however so we want to provide other ways for them to login. 

### Key Features in Order of Importance
- Review of possible APIs for phone support
- Registration by phone numbers, see the [Decision Record](https://github.com/Cadasta/decision-records/blob/master/DR_0003_supporting-phone-numbers.md) about how this should work.
- OAuth login
- Multi-Factor Authentication

**Possible mentor:** @oliverroick, @amplifi

**Comment by valaparthvi** [comment]
Hey , I would like to work on this issue as part of Outreachy. So how do I get started?

**Comment by wonderchook** [comment]
@valaparthvi Thanks for your interest. what is not clear about how to get started in the instructions above?

**Comment by valaparthvi** [comment]
@wonderchook I have started working on bugs mentioned in the above link, and I've already submitted a PR for issue [#1105](https://github.com/Cadasta/cadasta-platform/issues/1105l) and I'm finding other bugs to work on.
What I am unclear is, am I supposed to apply for these projects as a part of Outreachy  or as a part of the application process for Outreachy. So it would be good if you could clear that for me.

**Comment by wonderchook** [comment]
@valaparthvi I'm not quite sure I understand your question. Are you asking if you should do the project as part of the outreachy application process? This project is the project for the Outreachy internship, not the project for applying. As part of your application to Outreachy you should outline a schedule and describe how you would approach the project.

**Comment by valaparthvi** [comment]
@wonderchook I am now clear. I understand that this is the project for Outreachy Internship. So I will outline a schedule and approach for this project in my Outreachy Application. Thank You.

**Comment by niharika1995** [comment]
Hi all,

I would like to work on this project as a part of Outreachy. I have pushed a PR at [#1202](https://github.com/Cadasta/cadasta-platform/pull/1202).

**Comment by valaparthvi** [comment]
@wonderchook, you mentioned in the Key Features about Review of possible API for phone support. There are many APIs which are not free. So does this APIs have to be Free and Open Sourced?

**Comment by wonderchook** [comment]
@valaparthvi no we would need to pay for a service. We would want to use Twilio: https://www.twilio.com/

In approaching it though we want the code to be as modular as possible so it would be possible to switch providers someday without too much hassle.

**Comment by niharika1995** [comment]
@wonderchook @amplifi @oliverroick What is the expected and the approx. peak number of registrations Cadasta will handle per minute (assuming 1 SMS/registration)? This would help me decide whether communicating with the Twilio API can be handled within the request-response cycle.

**Comment by niharika1995** [comment]
Also, which OAuth providers is Cadasta targetting? Should existing users who have registered through email be allowed to link and login through their phone numbers and OAuth providers?

**Comment by wonderchook** [comment]
@niharika1995 we aren't sure yet. I would suggest just doing it during the normal request-response cycle to start. Regarding specific OAuth providers, we'd want part of this project to involve doing research on options and then we'd decide. 

Yes existing users should be able to link their phone numbers or OAuth providers.

**Comment by valaparthvi** [comment]
For phone-based registration, there are many python packages available which generate OTP and also uses Twilio API to send sms for verifying phone number, [django-otp-twilio](http://pythonhosted.org/django-otp-twilio/) is one such package. So do we want to use such packages or code from scratch?

**Comment by aklife97** [comment]
Hi,
How do you intend to bring in Multi-Factor Authentication i.e. what do you think would be the other steps that should be fulfilled after the person enters the correct username and password?
Should it based on Mobile/Email OTP or the combination of any 2 or more of the login methods?

**Comment by amplifi** [comment]
@niharika1995 Assume we will be communicating with the Twilio API for this process.

**Comment by amplifi** [comment]
@niharika1995 Assume we would be starting with Google and Facebook for OAuth providers, with the possibility of adding others.

**Comment by amplifi** [comment]
@aklife97 For MFA, there should be three logical branches:

1. If a user has opted in, authenticate via password then via app-based TOTP.
2. If a user has not opted in to app-based TOTP, but has a registered phone number, authenticate via password then via SMS OTP.
3. If a user has not opted in to app-based TOTP, and does not have a registered phone number, authenticate via password then via email OTP.

**Comment by sourabhtk37** [comment]
@wonderchook [small doubt] suppose I am applying for GSOC and someone else is applying via Outreachy for this same, will both of them be selected or only one of the proposal?

**Comment by wonderchook** [comment]
@sourabhtk37 only one would be selected.

**Comment by sourabhtk37** [comment]
That's weird don't you think, consider both are different project(GSOC and Outreachy). Let me know your inputs.

**Comment by wonderchook** [comment]
@sourabhtk37 how is it weird? What is the point of having two people do the same project twice? We only need it coded once...

**Comment by sourabhtk37** [comment]
The point I'm making is that since cadasta has more resources at its expense (that's being part of gsoc & outreachy), it could have more projects instead of having common projects for both outreachy &gsoc.
Also, I am not expert on this, kindly share insights into why the need to have common projects instead of more projects.

**Comment by wonderchook** [comment]
@sourabhtk37 that implies we have infinite people to mentor, which we do not. It takes a significant amount of investment to mentor someone well and we are a small group of people.

**Comment by sourabhtk37** [comment]
Yeah, thought of that too.
Thanks so much @wonderchook

**Comment by valaparthvi** [comment]
For implementing MFA, are we looking for a specific service provider?
@wonderchook @oliverroick @amplifi

**Comment by aklife97** [comment]
Hi, my proposal has not been reviewed.
Can someone please see to it.
Thanks

**Comment by amplifi** [comment]
Implemented under Google Summer of Code 2017. Thanks, @valaparthvi!
