### ISSUE TITLE
Improve Automatic Test Coverage (QA)

### ISSUE THREAD

**Issue by SteadyCadence** [Cadasta/cadasta-project-ideas#17]
## Skills Needed

* Experience with a programming language (Python preferred) 
* Basic Understanding of python tests/specs and test Coverage
* Familiarity with Selenium

## First Task

Find a bug and attempt to fix it. You can find possible bugs [here](https://github.com/cadasta-platform/issues) or you can look for them yourself. 

If that goes well, review the [cadasta-test repo](https://github.com/Cadasta/cadasta-test) and add a missing test case. You will need to fork the project to your own account and do a pull request to submit it. Currently most of the test cases cover positive results where the user has done everything right. Try adding a negative test case, examples when the user uploads a file that doesn't work or doesn't meet the password requirements. (Remember be creative, don't necessarily use the two suggested, one idea is write a test case to cover the bug that you fixed!). 

## Project Description

This project aims to increase test coverage on the platform. We have great Unit Test coverage, but when we prepare to deploy a release we don't have a great way to completely test our staging site-- other than mostly manually. At the moment we use a combination of automatic and manual tests.  We would like to expand the list of automatic tests and scenarios in which we can test. In the last round of Outreachy we had an internship to begin creating these tests. This project continues that work. 

## Key Features in Order of Importance

* [Review and add to Manual Test Case list](https://docs.google.com/spreadsheets/d/1JmKVAmdQgjdzg8YhrSDtfBtWckkv7aq4-ZIZCmwbbwU/edit?usp=sharing)
* Write tests for cases listed above for the [cadasta-test repo](https://github.com/Cadasta/cadasta-test)
* Determine which use cases should have priority and need automatic tests.
* Explore ways of testing different browsers automatically (BroswerStack...)

Possible Mentor: @steadycadence, @dpalomino

**Comment by kpdp** [comment]
You can refer this wiki as well. https://github.com/Cadasta/cadasta-test/wiki/Cadasta-Test-Cases

**Comment by kpdp** [comment]
You can refer this wiki as well. https://github.com/Cadasta/cadasta-test/wiki/Cadasta-Test-Cases

**Comment by shailysangwan** [comment]
How to proceed after the completing the first task?
Fixed bug and added tests: https://github.com/Cadasta/cadasta-platform/pull/1134

**Comment by oliverroick** [comment]
@shailysangwan You either fix another bug or start preparing your application by thinking about how you want to approach the project your want to work on and start to develop a project plan.

**Comment by varunsharma** [comment]
Hey guys, I'm interested in this project for GSoC but I just noticed that label of GSoC is not set for this project. Is this project a part of GSoC 2017?

**Comment by SteadyCadence** [comment]
@varunsharma Yes, this project can be a part of GSoC.  Let me know if you have any further questions!

**Comment by varunsharma** [comment]
Thanks @SteadyCadence. I'm almost ready with my first PR. Thanks for clarifying.

**Comment by kaayushi** [comment]
Hi. Can someone please help me in finding the bugs associated with this project?

**Comment by oliverroick** [comment]
Hi @kaayushi, Look into the repository `cadasta-platform`, we marked relevant issue with the label "First Contribution Friendly". Before you start working on issues, it might be worth a look if there are already pull requests for that PR.

**Comment by KukkadapuSushma** [comment]
Hi, I am new here, As I couldn't find any discussion forum so have pinged here! Kindly add me / share an invite link to join the group. I am an open src contributor, previously worked for FOSSASIA. I would like to start y contributions to Cadasta! :)

**Comment by oliverroick** [comment]
@KukkadapuSushma You can find links to both the Google Group and Gitter in the Wiki. 

One thing to keep in mind: Given the lack of resources on our team, it is currently highly unlikely that we will be offering internships in the foreseeable future.

**Comment by KukkadapuSushma** [comment]
@oliverroick Thank you! I am currently not expecting anything, but would like to aim for winter -OutReachy program, 2017. :)

**Comment by oliverroick** [comment]
> but would like to aim for winter -OutReachy program, 2017.

That's what I meant, we probably will not be taking part in the next round of Outreachy (Winter 2017/18).

**Comment by amplifi** [comment]
Closing temporarily; to be re-opened when next participating in Outreachy or GSoC.
