### ISSUE TITLE
Research and Set-up a Cadasta Community Portal

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#3]
Cadasta is a very new open-source project. Software Development started just this year and we are just beginning to a build a community. One of the next steps is to put together structure of a portal for that community to come together. 

**Tasks for this project:**
1. Research potential software options for community portals. How do other communities work with each other? What works and what doesn't work as well?
2. Work with Cadasta to determine internal needs for community portal.
3. Determine partner needs for community portal.
4. Make recommendation of portal.
5. Design and Set-up initial portal structure (this will depend on the decision made regarding the portal)

**Skills Required:** Strong research and documentation skills. 

**Potential Mentors:** @wonderchook @theaglitter

**Initial Task for Application:** Write an initial feature matrix to serve as a base for research into types of community portal software.  This should include items such as software license of the portal, professional hosting available for the software (Software as a Service), forums available, integration with other logins (Google, Twitter, Facebook, etc), and additional features.

**Comment by priyankamandikal** [comment]
Hello! I am interested in knowing whether this project will be offered for this round of Outreachy. I did some initial lookup on what types of portals are available and which tools can be used for building online portals. I just thought I should stop by and enquire before getting down to documenting my work.

**Comment by wonderchook** [comment]
Use this ticket instead: https://github.com/Cadasta/cadasta-project-ideas/issues/7
