### ISSUE TITLE
Quickstart Guide on How to Document Land Rights Using Cadasta

### ISSUE THREAD

**Issue by wonderchook** [Cadasta/cadasta-project-ideas#4]
Cadasta is a very new open-source project. Software Development started just in 2015 and we are just beginning to a build a community. One of the missing pieces is a Quick Start guide for how to document ones land rights using Cadasta. 

**Tasks for this project:**
1. Create initial guide outline.
2. Write guide chapters.
3. Create graphics as appropriate for guide showing workflows. 
4. Obtain feedback on guide from community and partners. 
5. Edit guide based on feedback
6. Finalize and publish guide

**Skills Required:** Research, documentation skills and graphic design skills. 

**Potential Mentors:** @wonderchook @fhpichel

**Initial Contribution:** Make an initial attempt at the outline for the guide.

**Comment by wonderchook** [comment]
For more background on Cadasta here is a recent [presentation from FOSS4G](http://www.slideshare.net/wonderchook/cadasta-securing-property-rights-with-open-source).

**Comment by sandraemma03** [comment]
Hello, my name is sandra and i am interested in this project for Cadasta outreachy 2015.

**Comment by wonderchook** [comment]
Hi @sandraemma03 thanks for introducing yourself.

**Comment by sandraemma03** [comment]
Hi Kate Chapman,

I have researched and i can't find any tool on Cadasta to document
the rights. I want to ask if the platform is still under development

Thanks

On 10/17/15, Kate Chapman <notifications@github.com> wrote:
> Hi @sandraemma03 thanks for introducing yourself.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/Cadasta/cadasta-project-ideas/issues/4#issuecomment-148914784


-- 
*Sandra **Nsiany *

**Comment by sandraemma03** [comment]
Hi @wonderchook, I have done an initial attempt to the guideline and i want you to review. How can i submit it?

**Comment by wonderchook** [comment]
@sandraemma03 can you open a ticket and tag me in it with the guide attached?

**Comment by sandraemma03** [comment]
@wonderchook, i don't know how this is done. This is the link to my git repository for the guide. 
https://github.com/sandraemma03/cadasta-project-ideas

**Comment by wonderchook** [comment]
@sandraemma03 please try to work it out. You need to open an issue in github in this repository. You could try searching "opening an issue on github" if you need step by step instructions.

**Comment by sandraemma03** [comment]
@wonderchook, Thank you. I have open an issue as you asked but I can't attached the guide to it. I have researched and am stock. Please can you give me a clue?

**Comment by sandraemma03** [comment]
@wonderchook , I got a message from ian-ross and she said the application list has been shortlisted and i don't find myself in it. So i think am disqualified for this project.

**Comment by khushbuparakh** [comment]
I am khushbu and I am interested in this project for  Outreachy 16. So I need help in getting started with things.

**Comment by TheaGlitter** [comment]
Hello,
Thank you for your interest in our internship position. To get started,
please read the project description and task list. If you have specific
questions about the tasks let me know and I will be happy to answer them.

Best,
Thea Aldrich

**Comment by saijahnavi1537** [comment]
Hi, I am jahnavi. I am interested in doing this project. I had read about project description before making an outline as the initial task I just wanted to know if there is any guide previously written?

**Comment by wonderchook** [comment]
@saijahnavi1537 no there is not a previous guide.

This list is not exhaustive, but here are a few things a guide should include:

- What is land rights?
- Types of technology available for documentation
- What to think about before starting a project

Reading through Cadasta's website would be a good starting point, though you can find other resources by searching online as well.

**Comment by saijahnavi1537** [comment]
[CADASTA.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/150909/CADASTA.pdf)
@TheaGlitter  @wonderchook  Hey please look at the initial outline of guide (contents). And suggest me how to proceed.

**Comment by Prateechi** [comment]
Hi, I am Prateechi. This project seems interesting and i would like to be a part of it for Outreachy 2016. Can you please send me link to some guide so that i can match your requirements and expectations.
Thank you.

**Comment by wonderchook** [comment]
@Prateechi the point is that a guide doesn't exist. What information other than a guide would help you get started?

**Comment by Prateechi** [comment]
@wonderchook Alright. I will send you my work on this. I also wanted to know if project 'Community Knowledge and Resource Portal' also open. I will send you a rough draft for both projects.

**Comment by wonderchook** [comment]
@Prateechi yes the other project is also open. It is recommended you pick the project you are most passionate about and focus on that one. Then you can spend more energy on it and do a better job.

**Comment by Prateechi** [comment]
@wonderchook  Ok i will. Thank you.

**Comment by saijahnavi1537** [comment]
@TheaGlitter  Hi, I tried making rough outline of contents in Quick start guide. Can you please look through it, so that I can make changes in the guide.
[CADASTA.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/152208/CADASTA.pdf)

**Comment by ankita0000** [comment]
hello @wonderchook @fhpichel am ankita am interested in internship and looking forward to be associated
with cadasta, i am a student pursing my
engineering

**Comment by Prateechi** [comment]
Hi Kate @wonderchook ,
I have made a rough draft for the outline of the guide. I was hoping if i could mail the draft to you explaining the a little bit more about the approach.
You can send me a blank email on prateechi.singh345@gmail.com
I hope you will like it.
Thank You.

**Comment by wonderchook** [comment]
Hi @Prateechi if you could send us a link to your draft that would be great. Just paste it inline here.

**Comment by wonderchook** [comment]
@saijahnavi1537 thanks for the outline. The guide is intended to be more a guide on the actual land rights documentation process than guide to Cadasta's website. You might try playing with the Platform to get a better idea of the software as a good starting point.

**Comment by saijahnavi1537** [comment]
Hi @wonderchook  I have some doubts. I have checked demo of cadasta platform on the website. It included how to create project, maps and soo on. So now this guide should include that ryt? and What do u mean by actual land rights documentation?  Should it be more about wat are land rights? how are they documented before?  various technologies? disadvantages and advantages? and soo on.. But in main idea it is mentioned how to document land rights using cadasta. So the main focus should be on how can we use platform for documentation? am I missing smething

**Comment by wonderchook** [comment]
@saijahnavi1537 the guide should answer questions such as:

- What are land rights?
- What are some processes for documenting land rights? (for example mapping boundaries of community lands)
- Types of technologies that could be used in the documentation (imagery, GPS units, mobile phones)

The main focus shouldn't be the platform, but it is a key component of the guide.

**Comment by Prateechi** [comment]
Hi @wonderchook  @fhpichel 
I am attaching a rough draft for the outline of the guide. I hope you will like it. Please go through it and do share your views so that i can make changes accordingly.
Thank you .
![cadasta_content](https://cloud.githubusercontent.com/assets/13360749/13473243/8d220f18-e0de-11e5-9669-9a0b9ce79bc2.jpg)
![cadasta](https://cloud.githubusercontent.com/assets/13360749/13473244/8d8ee822-e0de-11e5-97fa-a20d912df39f.jpg)

**Comment by Prateechi** [comment]
Hi @wonderchook @fhpichel 
I am sending a rough draft for the outline of the guide. Please do see it and share your views so that i can make changes accordingly. If you need any more work as a microtask then do mention.
Thank You. Hope you will like it.
![cadasta](https://cloud.githubusercontent.com/assets/13360749/13473412/483fc902-e0df-11e5-9b67-deee2f50f028.jpg)
![cadasta_content](https://cloud.githubusercontent.com/assets/13360749/13473427/59951e1e-e0df-11e5-9dad-a35368dc63b5.jpg)

**Comment by saijahnavi1537** [comment]
[CADASTA_ver2.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/157308/CADASTA_ver2.pdf)
Hi @wonderchook @TheaGlitter , I tried to make some changes as per your suggestions. Kindly look through it and suggest modifications that are required.

**Comment by Prateechi** [comment]
Hi @wonderchook !
Generally Quick Start Guide are of max 12-14 pages. Therefore i kept the headings accordingly. If you need the detailed contents then i will make the changes accordingly. Do also specify a round about number of pages for the guide.
Thanks. :-)

**Comment by wonderchook** [comment]
@Prateechi ideally it should be shorter than that, I'd say 5 or 6 pages.

**Comment by wonderchook** [comment]
@saijahnavi1537 I think with content you are on the right track, we would probably cut some of the details in the interest of being concise. Do you have thoughts about the overall design of the guide?

**Comment by Prateechi** [comment]
@wonderchook , are there any other changes you think that I should make?

**Comment by saijahnavi1537** [comment]
Thanks @wonderchook  for your feedback.  As you have mentioned I will try to cut short some of details, as guide should be not more than 5 or 6 pages. My idea is once we fix with the contents page, we can add content corresponding to that sections and relevant flow diagrams. Should I make rough draft showing where flow diagrams, block diagrams can be added. What else should be included in the design? I don't know if it relevant or not, but it would be great if we add a video (animated) explaining the entire motive. (similar to: https://www.youtube.com/watch?v=EVEkF411iak). Please do suggest what should be my next move.

**Comment by wonderchook** [comment]
@Prateechi, I'm going to wait and have @fhpichel look it over he is the "land person". I'll mention for him to look. 

@saijahnavi1537 I think a rough draft sounds good. Thanks for sharing the video I hadn't seen that one. I think there are a couple different ways that audiences could potentially consume the quickstart guide. Some people are going to want to use it printed on paper. Others will be on their computers and view it through the web. It is possible to be creative the various delivery mechanisms of the materials. I think key is thinking how to have those ways be complementary, but also have the same key messages.

**Comment by Prateechi** [comment]
@wonderchook Alright. The Idea regarding animated video explaining the whole mechanism is good. Even a short animated video ad for about 20-30 sec will also be great, can be featured as a YouTube ad and will be useful for  creating awareness about the Cadasta organisation to masses.

**Comment by saijahnavi1537** [comment]
Hi @wonderchook  I am in process of making rough draft, will send that by tonight. Since there are different kinds of audience, I think the only difference comes in terms of graphic content. For the people who view it on computer has video tutorial, graphic content, formatting. So while  printing these attributes should be excluded. One way is for computer viewing we display them on web page and for printing we create a link which has another document  which doesn't have graphic content.

**Comment by saijahnavi1537** [comment]
Hi @wonderchook  
[CADASTA1.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/163782/CADASTA1.pdf) This is what I thought about overall design of guide. As the guide is restricted to be not more that 5-6 pages this design would be better rather than previous uploaded one. This is concise rather than previous one.   What do think about this design? With this previous design
[CADASTA.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/163816/CADASTA.pdf) it is occupying more space.

**Comment by GracielaC** [comment]
@wonderchook @fhpichel 
Hi, my name is Graciela. I'm really interested in this project: "Quickstart Guide on How to Document Land Rights Using Cadasta" through Outreachy 2016. I've done some research about Cadasta and land rights and it has made clear on what the guide's content should be. I want to start doing the initial attempt and I have a couple questions before I start:
- Who is the potential user for this guide? (I.e. age range? nationality? education? gender? financial status?)
- Should it have an specific size (i.e letter) or can I propose a different one ?

Thanks!

**Comment by saijahnavi1537** [comment]
@wonderchook  After looking at my design. Please tell me how to proceed with the next task.

**Comment by Prateechi** [comment]
Hi @wonderchook @fhpichel,
Please have a look at the rough draft i send and suggest changes so that i can improve it and work further on this project.
Thank You!

**Comment by cartoblu** [comment]
Hello @wonderchook @fhpichel,

My friend Julia Lawall has been bugging me to get involved with this project, and she knows me well!  I'm hooked!  Have spent past 3 days studying/absorbing Cadasta, details on land tenure issues. LOVE the "party-relationship-land" organization of Cadasta.  I will be submitting a quick start outline proposal.  It may take a few days to polish it, as I'm teaching this semester (international relations) and have one week until Spring Break :-).  I would like to be considered for the internship.  Right off the bat I'd suggest a different approach -- if it's REALLY meant to be a "quick start" -- then perhaps a decision tree-type organization may be most helpful.  With GIS, I like to organize user info into three basic categories: getting data in (from various sources), manipulating data (doing various things), and displaying (outputting) data.  I think the same idea would work well here.  On the "high" end, I'm envisioning a touch screen-type app that let's the user select what to read/do, on the "low" end a web page with SIMPLE language that translates easily (and accurately) and can be printed/pdf'ed, maybe even scaled to be pocket sized for distribution.

**Comment by cartoblu** [comment]
[Quick Start Guide for Cadasta.docx](https://github.com/Cadasta/cadasta-project-ideas/files/170256/Quick.Start.Guide.for.Cadasta.docx)
Above is first draft -- will polish ASAP :-)

**Comment by wonderchook** [comment]
@saijahnavi1537 don't worry about replicating all the information on the website. Think more along the lines for what are the possible steps someone needs to take. Visual design is less important at the moment than the structure.

**Comment by wonderchook** [comment]
@Prateechi where is the draft you are referring?

**Comment by wonderchook** [comment]
@GracielaC 

The users could be varied in their technology knowledge. I would say assume a basic level of computer/internet literacy. We would eventually also translate into other languages. 

As far as format feel free to suggest something.

**Comment by wonderchook** [comment]
@cartoblu I like the design tree idea. I can imagine that fitting well into a web based guide a "choose your own adventure" type path.

**Comment by Prateechi** [comment]
Hi @wonderchook @fhpichel,
As I can see that the potential users are mostly people with basic understanding of computers and mobile phones, I have incorporated some changes in the draft accordingly. I feel that the quick start guide should be in both electronic and non-electronic form. 

In electronic format, the guide can be in the form of an app or a webpage link. A nice interactive guide will keep the users interested and will make their work a lot easier. All kinds of guides to document land rights that we plan should be in an interactive **pictorial format**. The links for the paper form guide are(a rough design):

[Cadasta.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/171137/Cadasta.pdf)

[Cadasta_content.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/171139/Cadasta_content.pdf)

The link depicting functionality of the guide in the form of a flowchart:
[Cadasta draft1.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/171145/Cadasta.draft1.pdf)

**Comment by shitaljagtap** [comment]
Hi @wonderchook 

I am interested in the project "Quickstart Guide on How to Document Land Rights Using Cadasta" and would like to apply for the same. This would be the great opportunity for me to get associated with CADASTA and know more about the work they do. 

 I have made my first attempt to create the outline of the Guide and have created 2 templates to get an idea about the design of the Guide.
[CADASTA_1.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/171165/CADASTA_1.pdf)
[CADASTA_2.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/171166/CADASTA_2.pdf)

Please review attached 2 files and let me know your comments. 

Thanks & Regards,
Shital

**Comment by shitaljagtap** [comment]
Hi @wonderchook 

Could you please have a look at the drafts I have submitted and let me know your feedback ?
It will help me to understand whether I am on the right track. 

Thanks & Regards,
Shital

**Comment by wonderchook** [comment]
@Prateechi the content draft is okay. There should be a section on the "why" they would want to use the software as well.

**Comment by wonderchook** [comment]
@shitaljagtap I like the design it follows our brand quite well. Could you also think about an outline of more specific content that would be in there?

**Comment by shitaljagtap** [comment]
Hi @wonderchook 

Thanks for the feedback. 
I have created the outline of the Quick Guide with more specific content. 

Please find the attached pdf and let me know your comments. 
[Quick Guide Outline.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/177750/Quick.Guide.Outline.pdf)

Thanks & Regards,
Shital

**Comment by Prateechi** [comment]
Hi @wonderchook,
I have added in the draft the point you mentioned. I tried to answer the question why the users would want to use the software. 
Please do have a look and further share your views.

Thanks!

[Cadasta draft2.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/178323/Cadasta.draft2.pdf)

**Comment by SonaliAg** [comment]
Hi @wonderchook @fhpichel 
I am Sonali Agrawal and I am interested in this project . I am a engineering student and interested in GIS. [Here ](https://github.com/SonaliAg/Cadasta/wiki/Quickstart-Guide-on-How-to-Document-Land-Rights-Using-Cadasta--Initial-Task)is my initial task for this project. Waiting for the comments.

[OutlineQuickStartGuideforCadasta.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/181306/OutlineQuickStartGuideforCadasta.pdf)

**Comment by SonaliAg** [comment]
@wonderchook can you have a look at my submission [here](https://github.com/SonaliAg/Cadasta/wiki/Quickstart-Guide-on-How-to-Document-Land-Rights-Using-Cadasta--Initial-Task)

**Comment by cartoblu** [comment]
Hi @wonderchook,

Just a couple quick questions:  Is the "Cadasta" logo font publicly available/free?  Also, with the privacy offered to Cadasta users:  Will Cadasta provide server space for users?  I'm assuming this in keeping with land rights mapping goals ... Or do users store their data on their own devices, and "upload" if they choose to share?  Second option would require user hardware (?).  Thanks!

**Comment by wonderchook** [comment]
Hi @cartoblu: 

You mean the logo and the tag line together? I don't think it is in a easy place to download at the moment but I can work on that being somewhere as a resource. 

The main technology is a web platform which provides server space for the users. Users will in many cases have to collect the data while disconnected and then upload it once they have internet access. So some users might need mobile phones, though it would also be possible to edit through a web interface.

**Comment by cartoblu** [comment]
@wonderchook Thanks, Kate, I found a Futura Light that approximates it, that'll do for this draft.
 And thanks for the info! :-)The off-site server space for users is a wonderful aspect of this project.

**Comment by cartoblu** [comment]
Hello to you all @wonderchook, @fhpichel, @TheaGlitter!  Here is a  graphic representation of a quick start user's guide.  I designed it too be a true "quick start" -- to get a user up and running, with the option of doing/learning a little here and there, if needed, or working all the way through.  The turquoise ribbon represents a possible (common?) path through the process.  Each "station" along the turquoise ribbon would be clickable to another page.  Am writing up suggested content for each "station"; will post soon.  Would like user to be able to pick/print station info as needed to print custom guides.  For example, printing data entry/editing guides for helpers, or issue/advocacy facts to pass out to garner community/political support.  Would also offer option of a complete guide to be printed.  More soon.
![cadasta-quick-start-copy 1](https://cloud.githubusercontent.com/assets/17715949/13934781/e4303404-ef81-11e5-8265-fae571e9eea0.jpeg)

**Comment by cartoblu** [comment]
Feedback is ALWAYS welcome (forgot to add that). :-)

**Comment by cartoblu** [comment]
Hello once again @wonderchook, @fhpichel, @TheaGlitter, Here is an outline for clickable pages ... can also be reconfigured to a PDF doc for download (when complete).  I'm imagining a "Quick Start" tab on the Cadasta Landing page which would lead to all this ... so I minimized the placement of the "Land Tenure/Why Cadasta?" sections b/c they are on the landing page also.  Hope that make sense! :-)
Thank you for all of your work on this issue/software.  This is exciting work and I've shared it with my POLS 319 International Relations students this semester.  Thank you also for providing the opportunity to contribute.  I've enjoyed the challenge! --Teresa
[Quick Start Outline.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/183351/Quick.Start.Outline.pdf)

**Comment by MMBazel** [comment]
@cartoblu : Love piktochart! Great choice! :+1:

**Comment by wonderchook** [comment]
Just a reminder to everyone that application deadlines are approaching. 

https://outreachy.gnome.org

**Comment by shitaljagtap** [comment]
Hi @wonderchook @fhpichel

I have submitted the outline of the Quick Guide with more specific content in the previous post.

It will be great if could you review it and let me know if I am on the right track. 

If you want any further details with the guideline, please let me know. I will provide it.

Thanks & Regards,
Shital

**Comment by Prateechi** [comment]
Hi @wonderchook,
Though the application submission is over but can I still contribute to the organisation (this project)?
I would love to help as the concept of organisation Cadasta in itself is really amazing and i can imagine that its use can actually change people's life especially in under developing countries.  :-)
So, do let me know if there is any work. :-)  
Thanks!
