### ISSUE TITLE
Community Knowledge and Resource Portal

### ISSUE THREAD

**Issue by TheaGlitter** [Cadasta/cadasta-project-ideas#7]
# This Project is Closed to New Applications. There are many people already interested, please look for another project or organization. 

#3 The Cadasta Platform is a relatively new open-source project working to build a fit-for-purpose land and resource rights management system. When deployed alongside equitable and inclusive programs, this technology has the power to democratize the documentation and safe storage of land and resource rights in places where they do not exist today.  Over the last year our technology team got software development started and we built the foundation of a vibrant and diverse community. We had a great experience with Outreachy in the past and are excited to extend some non/less technical internship opportunities to students this semester. 

One of the next steps is to put together a portal  where our community can come to find a variety of land and resource rights and open source technology related materials. We are looking for an intern to research and help design our Community Portal.

Tasks for this project:

1. Research potential software options for community and resource sharing portals. How do other communities work with each other? What works and what doesn't work as well? 

2. Work with Cadasta staff to determine internal needs for a resource and knowledge portal.

3. Determine partner needs for community portal. Is there any way we can collaborate with others who have similar needs?

4. Make recommendation on which tools we should use for our Community Portal.

5. Design and Set-up initial portal structure (this will depend on the decision made regarding the portal)

Skills Required: Strong research and documentation skills.

Potential Mentors: @wonderchook @theaglitter

Initial Task for Application: Research potential software options for community and resource sharing portals. What works and what doesn't work as well? Is there any way we can collaborate with others who have similar needs?

**Comment by priyankamandikal** [comment]
I am Priyanka Mandikal and I am interested in applying for the Outreachy project on Community Portal Development for Cadasta. I felt I need more information on how Cadasta operates before writing the initial draft for task 1 i.e researching community portal software options. Nevertheless I went ahead and prepared a rough draft of what I think about the community options for Cadasta. Let me know how I can send you the draft for feedback.

Thanks!

**Comment by wonderchook** [comment]
@priyankamandikal if you could just include a link to what you have worked on here that would be great.

**Comment by priyankamandikal** [comment]
This is just a rough draft. A little feedback would be helpful before proceeding further.
[Report Link](https://github.com/priyankamandikal/cadasta-community-dev/wiki)

**Comment by TheaGlitter** [comment]
Hello @priyankamandikal . Thank you so much so sharing your draft. I read through it and I like the way you are structuring the analysis. I will share some of the initial strategy documents I have developed that explain in more detail the Cadasta community. I would also be more than happy to jump on a skype call to discuss any questions you have about the organization or the internship. My skype id is thea.clay. I will send you a link to the community documents which may help provide more context.

Best,
Thea

**Comment by priyankamandikal** [comment]
Hi Thea!

I am looking forward to having a Skype call with you! Before that however, I would like to go over the community documents and discuss them over the call. If you could link me to the documents, so that I can study them, it would be great!

**Comment by TheaGlitter** [comment]
Sure, I will pull more information together and post it to the Issue early next week.

**Comment by ankita0000** [comment]
hi @wonderchook @theaglitter  am ankita am interested in
internship and looking forward to be associated
with cadasta ,i am a student pursing my
engineering .

**Comment by techchic** [comment]
Greetings from Kenya, @wonderchook and @theaglitter.
My name is Dorcas,I am very interested in contributing for Cadasta especially this particular project.

**Comment by wonderchook** [comment]
hi @techchic nice to meet you!

**Comment by ankita0000** [comment]
@TheaGlitter @wonderchook Please check the rough idea i have made and give me the feedback 

[Project ](https://github.com/ankita0000/management/blob/master/project.pdf)

**Comment by techchic** [comment]
[Research 1](https://github.com/techchic/Cadasta/wiki).
 Feel free to give me your feedback at your earliest convince.@TheaGlitter  @wonderchook

**Comment by wonderchook** [comment]
hi @ankita0000 we are more interested in how people interested in land or using the Cadasta platform can discuss and share what they are doing, recommend tools. 

Thanks @techchic can you also expand the 2nd part to look at what free culture communities do to share as well? I think we didn't well define what community means with regards to a community portal.

**Comment by techchic** [comment]
Hello @wonderchook  thanks for the feedback... Here's a a [link](https://github.com/techchic/Cadasta/wiki/How-do-other-communities-work-with-each-other%3F-What-works-and-what-doesn't-work-as-well%3F) to what have done so far.

**Comment by wonderchook** [comment]
Hi @techchic I like your content. For this project we were looking for more a web portal to help people share information. I think you might be interested in the Quickstart guide project: https://github.com/Cadasta/cadasta-project-ideas/issues/4

**Comment by SonaliAg** [comment]
Hi @wonderchook @TheaGlitter @fhpichel 
I am Sonali Agrawal and I am interested in this project . I am a engineering student and interested in GIS. [Here](https://github.com/SonaliAg/Cadasta/wiki/Community-Knowledge-and-Resource-Portal---Initial-Task) is my initial task for this project. Waiting for the comments

**Comment by jagtapkirti** [comment]
Hi  @wonderchook @TheaGlitter

My name is Kirti. I have done my Bachelor of Engineering in Information Technology. I am interested in
this project. Please find the document attached and provide me your feedback.

[Community Knowledge and Resource Portal.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/181737/Community.Knowledge.and.Resource.Portal.pdf)
 
I am little bit confused about the question "Is there any way we can collaborate with others who have similar needs?". 
Do you mean the other organizations which are also working on protecting land rights by "others who have similar needs" ?
Please clarify the meaning of "others who have similar needs". 

Thanks 
Kirti

**Comment by ankita0000** [comment]
Hello @TheaGlitter  @wonderchook

Community portal potential software i do understand but the major question i would like to ask cadasta is willing to share its tools for free of cost to others in community and also 

what is the exact agenda because when i went through the website
I had two queries: 
1.High level of interaction among community members
2.Development of software tools for sharing

If a community portal is to be built then opting for CMS Content management System can be good choice Drupal and wordpress can be great choices. 

or else making a customized web application for all community through interaction can be done can be great 

Community portal potentiality and its reach out depends on lot of factors what is the exact point
last time i expressed customized cms then i got reply tools but if we opt direct foss tools without optimizing them then can we leverage the usage ?

**Comment by ankita0000** [comment]
and one more question regarding the running of the community portal are you looking for financial model for resource building.

thanks

**Comment by wonderchook** [comment]
@jagtapkirti thanks for your submission. It would be beneficial to show some of your research into what other online communities are using for this type of sharing.

**Comment by wonderchook** [comment]
@ankita0000 we hope not to build something from scratch. Ideally we'd use existing software. I'm not quite sure I understand your queries. Could you try rewording them?

**Comment by wonderchook** [comment]
@ankita0000 we don't need a financial model at the moment.

**Comment by SonaliAg** [comment]
@wonderchook  can you please look at my submission. [here](https://github.com/SonaliAg/Cadasta/wiki/Community-Knowledge-and-Resource-Portal---Initial-Task)

**Comment by ankita0000** [comment]
hi @TheaGlitter  @wonderchook 
This is the rough idea i have made,please check it and give me the feedback

These are the softwares used for online portals:
[project.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/183872/project.pdf)

**Comment by wonderchook** [comment]
@ankita0000 thanks for submission Having a table for easy comparison including items such as general cost, if we would host the software or is hosting available, is it open source, etc would be useful.

**Comment by ankita0000** [comment]
@wonderchook  thank you for the feedback i will be sending the details in sometime.

**Comment by ankita0000** [comment]
@wonderchook this is the idea please give me the feedback

[research1.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/184665/research1.pdf)
[research2.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/184666/research2.pdf)

**Comment by ankita0000** [comment]
specifications for the research1 framework are presented in tabular form also comes with sample documentation i.e reasearch2 that how we should choose between them

**Comment by ankita0000** [comment]
hello @wonderchook 
why is it important to choose between the platforms or softwares because if we dont figure out our audience and respond then building community portal cant reach the goals we keep on organizational level .

[guide to choose .pdf](https://github.com/Cadasta/cadasta-project-ideas/files/184714/guide.to.choose.pdf)

**Comment by jagtapkirti** [comment]
@wonderchook  
Thanks for your feedback.
I'll work and get information on what other online communities are using for this type of sharing and submit it in some time.

Thanks 
Kirti

**Comment by jagtapkirti** [comment]
Hi  @wonderchook @theaglitter

Apologies for the late reply. 
Please find attached pdf which contains the research about what other online communities are using for resource sharing. 
[Community Knowledge and Resource Portal.pdf](https://github.com/Cadasta/cadasta-project-ideas/files/211770/Community.Knowledge.and.Resource.Portal.pdf)

Thanks
Kirti

**Comment by ankita0000** [comment]
hello @TheaGlitter  @wonderchook 

can some one officially confirm me whether application phase got completed or not because last date got completed a lot earlier, still applications and work is considered can some one confirm me

**Comment by zeddmaxx** [comment]
Hello!
I am Zoya an Engineering undergrad student.
I really like the idea of this project and would like to start contributing to it soon!

**Comment by wonderchook** [comment]
hi @zeddmaxx this particular project is closed. There will be others opened and available on Monday.
